/**
 * NÖMA · Catálogo demo.
 * Estructura pensada para migrar fácil a Shopify (handle, variantes, tags, colección).
 */
window.NOMA = {
  moneda: 'USD',
  envioGratis: 100,

  categorias: {
    aromas: { nombre: 'Aromas', titulo: 'Aromas', texto: 'Velas y difusores para que cada ambiente tenga su propio clima.' },
    ceramica: { nombre: 'Cerámica', titulo: 'Cerámica', texto: 'Piezas hechas a mano, con la huella de quien las moldeó.' },
    decoracion: { nombre: 'Decoración', titulo: 'Objetos', texto: 'Piezas para darle personalidad a cada rincón.' },
    textiles: { nombre: 'Textiles', titulo: 'Textiles', texto: 'Texturas nobles para abrigar el día a día.' },
    sets: { nombre: 'Sets', titulo: 'Sets', texto: 'Pequeños rituales, listos para regalar (o regalarte).' },
  },

  colores: {
    ambar: { nombre: 'Ámbar', hex: '#C4874F' },
    crudo: { nombre: 'Crudo', hex: '#EFE8DC' },
    salvia: { nombre: 'Salvia', hex: '#66735D' },
    terracota: { nombre: 'Terracota', hex: '#B8755D' },
    arena: { nombre: 'Arena', hex: '#C8B9A3' },
  },

  productos: [
    {
      id: 'vela-ambar',
      nombre: 'Vela Ámbar',
      categoria: 'aromas',
      precio: 32,
      color: 'ambar',
      nuevo: false,
      orden: 1,
      fecha: '2026-06-02',
      opcion: { nombre: 'Tamaño', valores: [{ v: '200 g', precio: 32 }, { v: '400 g', precio: 48 }] },
      breve: 'Cera de soja, ámbar y vainilla tostada. Una luz cálida para el final del día.',
      descripcion: [
        'La Vela Ámbar nació para ese momento en que la casa baja el volumen. Notas de ámbar, vainilla tostada y un fondo suave de madera que se quedan en el ambiente sin invadirlo.',
        'Vertida a mano en pequeñas tandas con cera de soja y mecha de algodón, en un vaso de vidrio ámbar que después podés reutilizar como portalápices, maceta o vaso de agua.',
      ],
      detalles: { Aroma: 'Ámbar · vainilla tostada · cedro', Duración: '45 h (200 g) · 80 h (400 g)', Materiales: 'Cera de soja, mecha de algodón, vidrio', Medidas: '8 × 9 cm (200 g)' },
      cuidados: 'La primera vez, dejala encendida hasta que toda la superficie se derrita. Recortá la mecha a 5 mm antes de cada uso.',
      combina: ['bandeja-terra', 'difusor-bosque'],
    },
    {
      id: 'vela-santal',
      nombre: 'Vela Santal',
      categoria: 'aromas',
      precio: 34,
      color: 'crudo',
      nuevo: true,
      pocas: true,
      orden: 5,
      fecha: '2026-09-10',
      opcion: { nombre: 'Tamaño', valores: [{ v: '200 g', precio: 34 }, { v: '400 g', precio: 52 }] },
      breve: 'Sándalo, higo y almizcle blanco en un vaso de cerámica cruda.',
      descripcion: [
        'Santal es la vela de los domingos lentos: sándalo cremoso, una nota verde de higo y almizcle blanco que abriga sin pesar.',
        'El vaso es de cerámica esmaltada por dentro y cruda por fuera, con tapa. Cuando termina la vela, queda una pieza para siempre.',
      ],
      detalles: { Aroma: 'Sándalo · higo · almizcle blanco', Duración: '45 h (200 g) · 80 h (400 g)', Materiales: 'Cera de soja, cerámica, mecha de algodón', Medidas: '9 × 9 cm (200 g)' },
      cuidados: 'No la dejes encendida más de 4 horas seguidas. Tapala al apagarla para conservar el aroma.',
      combina: ['cuenco-siena', 'manta-lino'],
    },
    {
      id: 'difusor-bosque',
      nombre: 'Difusor Bosque',
      categoria: 'aromas',
      precio: 35,
      color: 'salvia',
      nuevo: false,
      orden: 4,
      fecha: '2026-04-18',
      opcion: null,
      breve: 'Pino, musgo y hojas verdes. El aire de afuera, adentro.',
      descripcion: [
        'Bosque trae la sensación de abrir la ventana después de la lluvia: pino, musgo húmedo, hojas verdes y un toque de bergamota.',
        'Difusión constante durante semanas, sin llama ni electricidad. Ideal para entradas, baños y rincones de lectura.',
      ],
      detalles: { Aroma: 'Pino · musgo · bergamota', Duración: '8 a 10 semanas', Contenido: '200 ml + 8 varillas de ratán', Medidas: '7 × 14 cm' },
      cuidados: 'Girá las varillas una vez por semana para renovar el aroma. Alejalo de superficies de madera lustrada.',
      combina: ['vela-ambar', 'bandeja-terra'],
    },
    {
      id: 'jarron-arco',
      nombre: 'Jarrón Arco',
      categoria: 'ceramica',
      precio: 48,
      color: 'terracota',
      nuevo: true,
      orden: 2,
      fecha: '2026-09-01',
      opcion: { nombre: 'Color', valores: [{ v: 'Terracota', precio: 48 }, { v: 'Crudo', precio: 48 }, { v: 'Salvia', precio: 48, agotado: true }] },
      breve: 'Cerámica torneada a mano con un arco en relieve. Solo, ya es una escena.',
      descripcion: [
        'El Jarrón Arco se tornea a mano en un pequeño taller, pieza por pieza. El arco en relieve está dibujado con los dedos sobre la arcilla fresca: por eso ningún jarrón es exactamente igual a otro.',
        'Esmaltado por dentro para que puedas usarlo con agua y flores frescas, o dejalo vacío: su forma ya ocupa el espacio.',
      ],
      detalles: { Materiales: 'Gres torneado a mano, esmalte interior', Medidas: '14 × 24 cm', Origen: 'Hecho a mano en un taller local', Nota: 'Cada pieza tiene variaciones únicas' },
      cuidados: 'Lavar a mano con agua tibia. No apto para lavavajillas.',
      combina: ['cuenco-siena', 'manta-lino'],
    },
    {
      id: 'bandeja-terra',
      nombre: 'Bandeja Terra',
      categoria: 'decoracion',
      precio: 39,
      color: 'terracota',
      nuevo: false,
      orden: 3,
      fecha: '2026-03-05',
      opcion: null,
      breve: 'Una base para ordenar lo lindo: velas, llaves, anillos o el café de la mañana.',
      descripcion: [
        'Terra es la pieza que ordena todo lo demás. Una bandeja ovalada de cerámica con borde suave, pensada para agrupar pequeños objetos y convertirlos en una composición.',
        'Sobre la mesa de luz, en la entrada o en el baño: donde la pongas, arma un rincón.',
      ],
      detalles: { Materiales: 'Cerámica esmaltada', Medidas: '32 × 20 cm', Peso: '850 g' },
      cuidados: 'Limpiar con un paño húmedo. Apta para lavavajillas en ciclo suave.',
      combina: ['vela-ambar', 'difusor-bosque'],
    },
    {
      id: 'cuenco-siena',
      nombre: 'Cuenco Siena',
      categoria: 'ceramica',
      precio: 28,
      color: 'terracota',
      nuevo: false,
      orden: 6,
      fecha: '2026-02-11',
      opcion: { nombre: 'Tamaño', valores: [{ v: 'Chico', precio: 28 }, { v: 'Grande', precio: 38 }] },
      breve: 'Un cuenco de esmalte tierra para frutas, llaves o nada en particular.',
      descripcion: [
        'Siena tiene el color de la tierra después del sol. Un cuenco amplio, de paredes finas, con un esmalte que cambia de tono según la luz.',
        'Funciona en la mesa, en la cocina o como pieza decorativa en un estante.',
      ],
      detalles: { Materiales: 'Gres esmaltado', Medidas: '16 × 7 cm (chico) · 22 × 9 cm (grande)', Uso: 'Apto alimentos' },
      cuidados: 'Apto lavavajillas. No apto microondas.',
      combina: ['jarron-arco', 'bandeja-terra'],
    },
    {
      id: 'manta-lino',
      nombre: 'Manta Lino',
      categoria: 'textiles',
      precio: 64,
      color: 'arena',
      nuevo: false,
      orden: 7,
      fecha: '2026-05-20',
      opcion: { nombre: 'Color', valores: [{ v: 'Arena', precio: 64 }, { v: 'Salvia', precio: 64 }] },
      breve: 'Lino lavado a la piedra, con flecos anudados a mano.',
      descripcion: [
        'Suave desde el primer día y mejor con cada lavado. La Manta Lino está hecha de lino lavado a la piedra, liviana para el verano y perfecta en capas en invierno.',
        'Los flecos se anudan a mano, uno por uno. Sobre el sillón, a los pies de la cama o para llevar a un picnic.',
      ],
      detalles: { Materiales: '100 % lino lavado a la piedra', Medidas: '130 × 170 cm', Peso: '720 g' },
      cuidados: 'Lavar en frío, ciclo delicado. Secar a la sombra. Se ve mejor sin planchar.',
      combina: ['vela-santal', 'jarron-arco'],
    },
    {
      id: 'set-ritual',
      nombre: 'Set Ritual de Noche',
      categoria: 'sets',
      precio: 89,
      precioAnterior: 106,
      pocas: true,
      color: 'ambar',
      nuevo: true,
      orden: 0,
      fecha: '2026-09-20',
      opcion: null,
      breve: 'Vela Ámbar + Difusor Bosque + Bandeja Terra, en una caja para regalar.',
      descripcion: [
        'Un pequeño ritual para bajar el ritmo, apagar el ruido y hacer espacio para vos. El set reúne tres de nuestras piezas favoritas en una caja de cartón reciclado, con papel de seda y una tarjeta escrita a mano.',
        'Encendé la vela, dejá que el difusor haga lo suyo y usá la bandeja para armar tu rincón. Una hora para vos, todas las noches.',
      ],
      incluye: ['Vela Ámbar 200 g', 'Difusor Bosque 200 ml', 'Bandeja Terra'],
      detalles: { Incluye: 'Vela Ámbar · Difusor Bosque · Bandeja Terra', Packaging: 'Caja de regalo + tarjeta escrita a mano', Ahorro: 'USD 17 frente a comprar por separado' },
      cuidados: 'Ver los cuidados de cada pieza en su página.',
      combina: ['manta-lino', 'vela-santal'],
    },
  ],
};
